# Generated by Django 5.0.1 on 2024-02-11 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(default=datetime.datetime(2024, 2, 11, 15, 11, 15, 619712, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
