# Generated by Django 5.0.1 on 2024-06-22 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('Excellet', 'Excellet'), ('Good', 'Good'), ('Ok', 'Ok'), ('Bad', 'Bad')], default='Good', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('privacy', models.CharField(choices=[('PU', 'Public'), ('PR', 'Private'), ('FR', 'Friends Only')], default='PR', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journeys',
                'ordering': ['-created'],
            },
        ),
    ]
