# Generated by Django 5.0.1 on 2024-06-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyStatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journy',
            name='mood',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Ok', 'Ok'), ('Bad', 'Bad')], default='Good', max_length=10),
        ),
    ]
