# Generated by Django 5.0.1 on 2024-06-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyStatus', '0002_alter_journy_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journy',
            name='notes',
            field=models.TextField(),
        ),
    ]
