# Generated by Django 5.0.1 on 2024-06-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyStatus', '0003_alter_journy_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journy',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Friends Only', 'Friends Only')], default='PR', max_length=12),
        ),
    ]
