# Generated by Django 5.0.1 on 2024-06-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyStatus', '0004_alter_journy_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journy',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Friends only', 'Friends only')], default='PR', max_length=12),
        ),
    ]
