# Generated by Django 5.0.1 on 2024-06-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyStatus', '0005_alter_journy_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='journy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='journey_images/'),
        ),
        migrations.AddField(
            model_name='journy',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='journey_videos/'),
        ),
    ]
